### ISSUE TITLE
Add simple UI for noice denoiser

### ISSUE THREAD

**Issue by caron** [Autodesk/sitoa#14]
We should have some sort of UI for the noice denoiser for non-technical users.

**Comment by caron** [comment]
Going to just copy this as closely as possible...

https://support.solidangle.com/display/A5AFMUG/Arnold+Denoiser

**Comment by JenusL** [comment]
There's also the issue of the variance AOV and filter required to denoise an image with noice.
See MtoA ticket https://trac.solidangle.com/mtoa/ticket/3387

**Comment by JenusL** [comment]
The UI for noice is written in Python in MtoA. Do anyone see a problem if I also write it in Python so that most of the code can be copied, or should I rewrite it in JS like the other SItoA helpers?

**Comment by sjannuz** [comment]
No problem, thankyou

**Comment by caron** [comment]
Looks like this can be closed now with the merging of #53 and thanks @sjannuz for merging #29 to master
