### ISSUE TITLE
Add pick button for lights in Toon shader

### ISSUE THREAD

**Issue by JenusL** [Autodesk/sitoa#24]
We should add a pick button and handle object name translation so that we can easily pick lights in the Toon shader.
@sjannuz Had this to say about it:
> One thing about toon, is that the lights, if any, must be referenced by name, so we'd need a button to translate a picked light into its SItoA name. I can check what I was doing before camera_projection turned the projection camera into a node (was a string in Arnold 4).

**Comment by sjannuz** [comment]
Here is the mentioned change happened for camera_projection, in ParamsCommon.cpp

![camera_projection](https://user-images.githubusercontent.com/18032216/44794665-36157a00-aba9-11e8-9910-851a1577dbb6.jpg)

**Comment by JenusL** [comment]
I started to work on this yesterday and I'm done with the name translation.
I will investigate what Pick button solution to use and add that before I create a PR.

**Comment by sjannuz** [comment]
IIRC, what automagically adds the Pick button in ShaderDef.cpp is
`
      case AI_TYPE_NODE:
         return siShaderDataTypeReference;
`
This works for node parameters. You can probably add an exception for the toon lights, that are strings instead, and use that return type for them, instead of siShaderDataTypeString.
