### ISSUE TITLE
Please create devel branch and tag releases

### ISSUE THREAD

**Issue by JenusL** [Autodesk/sitoa#3]
Could there be a release created so we can have easy references to different states in the master branch.
It doesn't have to include binaries or any other files just needs to be a tag really.
The first tag (4.1.0) doesn't need any information at all but for later versions it would be good to have release notes.

**Comment by JenusL** [comment]
Would also be really good the create a `devel` branch that can merge the Pull Requests and from there we could push new releases to `master`.
This will provide proper git flow.

**Comment by sjannuz** [comment]
I tagged the initial master as 4.1 (the corresponding released version), and opened a develop branch

**Comment by sjannuz** [comment]
@JenusL , can you retarget your pull requests to be merged into develop ?

**Comment by JenusL** [comment]
@sjannuz Done! All PR are now rebased to the develop branch.

**Comment by kikou** [comment]
Why do we need a develop branch?

**Comment by JenusL** [comment]
@kikou It's just easier to test all the PRs together there first and when we're at a certain stage we create a PR from dev to master to create a new release. This way master is always deployable and stable.
It's like a git-flow / GitHub Flow hybrid.

**Comment by kikou** [comment]
@JenusL I get that, but another way is to have a master that is always deployable. If you want to experiment, you can use a feature branch. I'm just trying to keep it simple and stable.

**Comment by JenusL** [comment]
@kikou Yeah you can do it both ways. I just find this way to be a little bit more flexible on projects like this.
Think of the develop branch as being named `feat/a5.1.0` instead and my smaller PRs are merged into that. We have the benefit of be able to gather several PRs in to develop branch. And if we were to create a PR called SItoA 5.0.0 from develop to master right now, all of the commits would be included there. We could have discussions of what more to be included in 5.0.0 and have that PR open for a long time until we all agree that it's done and then merge it to master.

But I totally see your point as well. I mean we could just delete the develop branch after we merge into master and continue with just the GitHub Flow way. Just as long as we all work the same way :)
But I still think it would be nice to have 1 extra branch to be able to gather PRs in if required. But that name doesn't has to be develop... it could be a new branch for every feature that is big enough that it needs another level.

It was just that you asked me to create several smaller Pull Request and I thought that in that case it would be nice to have a way to group them together, hence the develop branch.

**Comment by JenusL** [comment]
Maybe we should remove the `develop` branch and create a new one that's called `release-candidate` or something like that instead. I think that's a better fitting name for what we want to use it for.
What do you think?
