### ISSUE TITLE
Add support for Color Managers

### ISSUE THREAD

**Issue by JenusL** [Autodesk/sitoa#31]
Since Softimage will never be updated to use OCIO we should at least add it to SItoA.
Let's expose `options.color_manager` in the render settings and add UI for `color_manager_ocio`.
[https://support.solidangle.com/display/A5NodeRef/color+managers](https://support.solidangle.com/display/A5NodeRef/color+managers)

**Comment by caron** [comment]
color temp on the camera?

**Comment by JenusL** [comment]
Oops… I really thought that existed by now but apparently not.
How are people using physical sky and temperature on lights/volumes and stuff like that in other packages?
There has to be some sort of white balance on the camera right?

**Comment by caron** [comment]
It makes sense adding color temp controls to the camera if those controls exist in Arnold. But I didn't think Arnold camera's had a color temp control.

**Comment by JenusL** [comment]
Yeah I thought those controls did exist but apparently not, which surprises me.
Anyway, with a color manager we can at least change rendering color space. That means spectral calculations that `physical_sky` and `blackbody` uses will be correct.
Our studio has been running all rendering and comp in ACEScg for several years now and be able to do that in SItoA as well would be really nice.

**Comment by JenusL** [comment]
I think I'm gonna start working on this next.

**Comment by JenusL** [comment]
So I started to work on this last night and I'm halfway there but I have some question that maybe @sjannuz could answer?
Is there anything special I need to do when exporting a node that doesn't have a Softimage counterpart?Does it has to be exported to the node map in order to export or is calling
`AtNode* var = AiNode("color_manager_ocio")` simply enough to export it?

I had a look at MtoA and it's node map has the methods `AddArnoldNode` which is calling `AddExistingArnoldNode` to add the color manager to the node map.
Do you think this is required in SItoA as well?

**Comment by JenusL** [comment]
I've figured everything out now so just have a bunch of cleanup before this is done.
But I will be goin to New York for a commercial shoot so I'll have to finish this when I get back in a week.

**Comment by caron** [comment]
no rush from me, we are probably the only ones that care about this project anymore :P

**Comment by JenusL** [comment]
Haha yeah that's probably true :)

**Comment by specularity** [comment]
+1 future user 👍 . Thans for keeping sitoa alive!

**Comment by JenusL** [comment]
Whoho!! Thanks RC!
