### ISSUE TITLE
Error: function ArnoldPassShaders_Init is missing

### ISSUE THREAD

**Issue by JenusL** [Autodesk/sitoa#36]
Just pressing the Edit button under Pass on the Render toolbar gives this message:
```
# ERROR : 2268 - This function is missing:
# <function: ArnoldPassShaders_Init>
# <path: C:\Users\lindg\Documents\GitHub\sitoa\dist\Softimage_2015_SP2\Addons\SItoA\Application\Plugins\ArnoldMenu.js>
# 
```
I guess this is a function that Softimage expects to be there for any renderer.
We should probably implement it and add some Arnold shaders to that menu. Like cryptomatte and some background shaders maybe.

**Comment by caron** [comment]
I think this is just the 'Arnold Pass Shaders' submenu that used to have the Volume Scattering, Physical Sky, and Background shaders.

**Comment by caron** [comment]
This is what is used to look like...

```
// pass sub-menu
function ArnoldPassShaders_Init(io_Context)
{
   var xsiMenu = io_Context.Source;
   xsiMenu.AddCallbackItem("Volume Scattering", "OnShadersMenu");
   xsiMenu.AddCallbackItem("Fog",               "OnShadersMenu");
   xsiMenu.AddSeparatorItem();
   xsiMenu.AddCallbackItem("Sky",               "OnShadersMenu");
}
```

**Comment by caron** [comment]
@JenusL I think we can close this?

**Comment by JenusL** [comment]
@caron Closed now. Was waiting for tickets to auto-close when pulled to master branch because I thought that would have happened by now.

**Comment by caron** [comment]
I didn't know they got auto closed when merged with master... I actually assumed they would get auto closed when they got merged with develop
