### ISSUE TITLE
Dependency Graph

### ISSUE THREAD

**Issue by JenusL** [Autodesk/sitoa#51]
Arnold 5.1 introduced a dependency graph:
> - **Node dependency graph (EXPERIMENTAL)**: a new node dependency graph allows tracking references between nodes, so that when a node is deleted or replaced, it can be automatically changed anywhere the node may have been referenced in the scene. It can be enabled using options.enable_dependency_graph. This is still a work in progress, so there are some unsupported cases, which will be addressed in a future release. (#6437)

While browsing through some code in MtoA I noticed that it's there and always enabled in interactive mode:
```
if (GetSessionOptions().IsInteractiveRender())
   AiNodeSetBool(options, "enable_dependency_graph", true);
```
Would it hurt to add it to SItoA as well?

I searched for a ticket in MtoA to explain it a little bit more and I found ticket [#3260](https://trac.solidangle.com/mtoa/ticket/3260)
Does SItoA, like MtoA, have a lot of that code that could be removed if we enable that option? Maybe this could even solve some crashes…
Let's see what old code/tickets we can find that is related to this in SItoA.

**Comment by sjannuz** [comment]
Adding the option does not hurt. Yes, there is quite some code in SItoA handling dependencies. It's a delicate part, of course, and I would not touch it for now.
