### ISSUE TITLE
Can't inspect Material

### ISSUE THREAD

**Issue by JenusL** [Autodesk/sitoa#65]
Looks like #40 introduced a nasty bug. It's impossible to inspect the Material node because it just jumps to standard_surface. This is because Material shows the closure PPG inside it.
This makes it impossible to choose OpenGL settings like the texture to show in the viewport.

**Comment by JenusL** [comment]
So I thought I would loop through all open PPGs and only run `InspectObj()` if `closure` is main content.
`Application.Desktop.ActiveLayout.Views` doesn't return any PPGs and I can't find any other way at all to get them.
I've tried all I can think of but can't really find a solution to this other than to remove the code completely.
@caron Any thoughts?

**Comment by caron** [comment]
Looking at it now...

**Comment by caron** [comment]
Hmm, this is tricky. Maybe we can inspect the material node also. `InspectObj` takes a string list so we can pass both the input and output of the `closure` node.

**Comment by JenusL** [comment]
Great thinking! So I just tried that and it doesn't work either :(
It creates an infinite recursion because Material wants to show closure so the logic runs over and over.

**Comment by caron** [comment]
Right, doh! I am fine removing it, it was just a 'nice' thing to have. Don't want to cause trouble.

**Comment by JenusL** [comment]
Created a revert PR.
I agree it was a nice thing to have. Maybe we can revisit it some time.
