### ISSUE TITLE
cryptomatte not showing in render tree?

### ISSUE THREAD

**Issue by caron** [Autodesk/sitoa#69]
I can't find `cryptomatte` under the Arnold/AOV category. When I add it using a script it shows up red without ports.

@JenusL Is it working for you?

**Comment by JenusL** [comment]
@caron Yes it's working fine here in feat/a5.3.0 branch.

**Comment by caron** [comment]
i had cryptomatte installed from alShaders maybe it was messing with it. i will try a fresh build of `feat/a.5.3.0` branch

**Comment by JenusL** [comment]
Yeah that's probably why.

**Comment by JenusL** [comment]
@caron Did you get this to work?

**Comment by caron** [comment]
i removed all references to the old cryptomatte and alshaders but still doesn't show up.

while trying to figure out what was going on i noticed the cryptomatte.dll in the plugins directory wasn't being installed correctly when i was switching between the different arnold core versions. i was building with 5.3.x and then switched to 5.2.x but the cryptomatte.dll wasn't being updated (either was alembic_proc.dll). isn't scons supposed to detect this and overwrite those .dlls?

i purged the arnold plugins directory and re ran `abuild install` and now i can see cryptomatte in the render tree. so the issue is actually with the build system.

**Comment by JenusL** [comment]
Hmm, yeah that's strange. Maybe we should look into that.

**Comment by JenusL** [comment]
Could you close this @caron?

**Comment by caron** [comment]
Its not exactly fixed, its a build issue.

**Comment by JenusL** [comment]
Ok cool I'll see if I can fix it.

**Comment by caron** [comment]
my guess is scons doesn't actually track those files the same way as it would the .dll files we are building in sitoa. ie. if the file exists then that is good enough.

**Comment by JenusL** [comment]
I found this https://scons.org/faq.html#Why_is_my_directory_only_updated_the_first_time.3F

**Comment by caron** [comment]
Ya, that looks like what I ran into when I researched it originally... I didn't like that idea cause that would mean polluting the Arnold API directory with this random file. Did I understand the suggested workaround correctly?

**Comment by JenusL** [comment]
You don't need a random file if the .dll files themselves has changed. And they have changed. Otherwise you wouldn't get a crash.
I fixed it now in https://github.com/Autodesk/sitoa/pull/76/commits/c9ac9a1a5f2e88c8d5c883a2c9ad2731071bda57

**Comment by caron** [comment]
That is what I thought it would do but it didn't... I see you changed the Install to pull the files instead of just the folder. That was enough for it to see the files were different then?

**Comment by JenusL** [comment]
Yes exactly. When it looked at the folder it only checked that the folder existed.
Now it checks all the files instead and it works as expected.

**Comment by caron** [comment]
Closing #69
