### ISSUE TITLE
optix_denoiser.dll not found

### ISSUE THREAD

**Issue by JenusL** [Autodesk/sitoa#8]
SItoA shows the following warning when rendering with Arnold 5.1.0.0

```
// WARNING : [arnold] unable to load dynamic library <local_workgroup_path>\Addons\SItoA\Application\Plugins\bin\nt-x86-64\optix_denoiser.dll: The specified module could not be found.
```
This doesn't make sense because the dll-file is clearly there in the folder with the rest of the core files.
I don't know if it's a problem on Linux as well.
The warning is harmless but annoying for now.
I'm guessing that the Optix Denoiser wouldn't work if it was implemented now.

**Comment by sjannuz** [comment]
In Max, we had to add the plugin's directory to PATH, I need to check this.

**Comment by JenusL** [comment]
I just added the location to PATH and the warning is gone. So seems to be the same as in Max then.
Any chance this could be fixed in the core?

**Comment by JenusL** [comment]
I started to look in to this and it's a bit tricky if we want it to work for both Win and Linux.
Does anyone know if we even get the warning on Linux?

**Comment by caron** [comment]
I haven't tested it on Linux so I can't help there. I think we should fix Windows and wait for the community to show us it isn't working on Linux.

**Comment by JenusL** [comment]
I agree. Lets put it inside an ifdef so we don't break Linux.

**Comment by JenusL** [comment]
I've started to work on this now so I will put up a PR tomorrow.
