### ISSUE TITLE
Hidden lights still visible in camera and transmission

### ISSUE THREAD

**Issue by JenusL** [Autodesk/sitoa#86]
Support for visible are lights were added in Arnold 5.3. In SItoA we always export all lights but set the intensity to 0 on hidden lights. This causes the light to disappear in Reflections, but it is showing up as black in Camera and Transmission.
Workaround right now is to just set camera and transmission to 0 as well on hidden lights,
But I still got some questions...
1. Why is Specular / Reflections just additive? Is there any plans to change this?
2. What is the proper way to disable a light in Arnold?

@sjannuz Maybe you got the answers for me?

**Comment by sjannuz** [comment]
Back in the days, that was the simpler way to support lights' enabling/disabling in IPR. But that was long ago, many enhancements have happened in Arnold around IPR support, including destroying and creating lights.
As it is, a more modern way to disable a light without destroying it is probably AiNodeSetDisabled.

**Comment by JenusL** [comment]
I tried AiNodeSetDisabled. It makes sense to use that in IPR but it doesn't work as expected when exporting to .ass. Do you think I should just skip exporting hidden lights when not in IPR?

**Comment by JenusL** [comment]
So I tested how it works in MAXtoA and there hidden lights are not exported at all. So I'm gonna do that here as well.
