### ISSUE TITLE
Support Arnold 7

### ISSUE THREAD

**Issue by JenusL** [Autodesk/sitoa#89]
Not so much new stuff but quite a few things have changed... especially color managers and denoising.

**Comment by maxol1** [comment]
hey i am not that good at compiling, is it possible to have the .addon compiled for Softimage 2015?
thanks ;)

**Comment by JenusL** [comment]
Yeah I'll probably release an addon when it's ready.

**Comment by IRONIC3D** [comment]
Thanks @JenusL

**Comment by JenusL** [comment]
@maxol1 @IRONIC3D Addon for windows can be downloaded from my releases here: https://github.com/JenusL/sitoa/releases

**Comment by IRONIC3D** [comment]
That's awesome @JenusL , thank you so much for adding those features.
