### ISSUE TITLE
Arnold Denoiser Noice issues

### ISSUE THREAD

**Issue by IRONIC3D** [Autodesk/sitoa#91]
Having an issue installing 7.0

```
# ERROR : 2229 - Traceback (most recent call last):
#   File "<Script Block 2>", line 41, in XSILoadPlugin
#     Application.LoadPlugin(XSIUtils.BuildPath(in_reg.OriginPath, 'ArnoldTools.js'))
#   File "<COMObject Application>", line 2, in LoadPlugin
# COM Error: Invalid argument.  UI Items should be specified as a 1D array of String/Value pairs. - [line 40 in C:\Users\xxx\Autodesk\Softimage_2015_R2-SP2\Addons\SItoA\Application\Plugins\ArnoldDenoiser.py]
```

The denoiser doesn't load and I cannot seem to be able to select another denoiser.

**Comment by JenusL** [comment]
So you get this issue when you install SItoA?
Have you followed the update guide: https://docs.arnoldrenderer.com/display/A5SItoAUG/Updating+SItoA

**Comment by IRONIC3D** [comment]
Thanks @JenusL , that solved it, I had to remove the preference file as well and that solved the issue.

One other question, I cannot seem to find any of the new imagers for denoising (oidn, optix, or even the tonemap ones) How can I add those? The menu item DLL shaders doesn't include them.

Thanks again

**Comment by JenusL** [comment]
@IRONIC3D Imagers are added as a Lens Shader to the Camera or Pass. First connect the node named `imager` and then plug any imager_* in to that.
If you add it to the Pass you also need to enable Lens Shaders on the Pass. (default is to only use Camera Lens Shaders).

**Comment by IRONIC3D** [comment]
Thanks @JenusL , that solved the issue. Appreciate your help.

**Comment by JenusL** [comment]
No problem.
@sjannuz Could you close this ticket please?
